// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (name)
VALUES ($1)
RETURNING id_course, name
`

func (q *Queries) CreateCourse(ctx context.Context, name string) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse, name)
	var i Course
	err := row.Scan(&i.IDCourse, &i.Name)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :execrows
DELETE FROM courses
WHERE id_course = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, idCourse uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCourse, idCourse)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCourseById = `-- name: GetCourseById :one
SELECT id_course, name FROM courses
WHERE id_course = $1
`

func (q *Queries) GetCourseById(ctx context.Context, idCourse uuid.UUID) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseById, idCourse)
	var i Course
	err := row.Scan(&i.IDCourse, &i.Name)
	return i, err
}

const getCourseByName = `-- name: GetCourseByName :one
SELECT id_course, name FROM courses
WHERE name = $1
`

func (q *Queries) GetCourseByName(ctx context.Context, name string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByName, name)
	var i Course
	err := row.Scan(&i.IDCourse, &i.Name)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id_course, name FROM courses
ORDER BY name
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.IDCourse, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourseName = `-- name: UpdateCourseName :one
UPDATE courses
SET name = $2
WHERE id_course = $1
RETURNING id_course, name
`

type UpdateCourseNameParams struct {
	IDCourse uuid.UUID `json:"id_course"`
	Name     string    `json:"name"`
}

func (q *Queries) UpdateCourseName(ctx context.Context, arg UpdateCourseNameParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, updateCourseName, arg.IDCourse, arg.Name)
	var i Course
	err := row.Scan(&i.IDCourse, &i.Name)
	return i, err
}
