// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inscriptions_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveBySemester = `-- name: CountActiveBySemester :one
SELECT COUNT(*) FROM inscriptions
WHERE id_semester = $1 AND active
`

func (q *Queries) CountActiveBySemester(ctx context.Context, idSemester uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveBySemester, idSemester)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInscription = `-- name: CreateInscription :one
INSERT INTO inscriptions (id_semester, email)
VALUES ($1, $2)
ON CONFLICT (id_semester, email)
DO UPDATE SET active = true
RETURNING id_inscription, id_semester, email, active, created_at
`

type CreateInscriptionParams struct {
	IDSemester uuid.UUID `json:"id_semester"`
	Email      string    `json:"email"`
}

// Si el email ya estaba inscripto en esa cursada, lo reactiva en lugar de
// fallar por la UNIQUE. Cubre el caso de volver a escanear el QR después de
// haberse dado de baja.
func (q *Queries) CreateInscription(ctx context.Context, arg CreateInscriptionParams) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, createInscription, arg.IDSemester, arg.Email)
	var i Inscription
	err := row.Scan(
		&i.IDInscription,
		&i.IDSemester,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInscription = `-- name: DeleteInscription :execrows
DELETE FROM inscriptions
WHERE id_inscription = $1
`

func (q *Queries) DeleteInscription(ctx context.Context, idInscription uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInscription, idInscription)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInscriptionByEmailAndSemester = `-- name: GetInscriptionByEmailAndSemester :one
SELECT id_inscription, id_semester, email, active, created_at FROM inscriptions
WHERE id_semester = $1 AND email = $2
`

type GetInscriptionByEmailAndSemesterParams struct {
	IDSemester uuid.UUID `json:"id_semester"`
	Email      string    `json:"email"`
}

// Decide qué mostrar en la pantalla del link: alta, baja o reactivación.
func (q *Queries) GetInscriptionByEmailAndSemester(ctx context.Context, arg GetInscriptionByEmailAndSemesterParams) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, getInscriptionByEmailAndSemester, arg.IDSemester, arg.Email)
	var i Inscription
	err := row.Scan(
		&i.IDInscription,
		&i.IDSemester,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getInscriptionById = `-- name: GetInscriptionById :one
SELECT id_inscription, id_semester, email, active, created_at FROM inscriptions
WHERE id_inscription = $1
`

func (q *Queries) GetInscriptionById(ctx context.Context, idInscription uuid.UUID) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, getInscriptionById, idInscription)
	var i Inscription
	err := row.Scan(
		&i.IDInscription,
		&i.IDSemester,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEmailsBySemester = `-- name: ListActiveEmailsBySemester :many
SELECT i.email
FROM inscriptions i
JOIN semesters s ON s.id_semester = i.id_semester
WHERE i.id_semester = $1
  AND i.active
  AND s.end_date >= CURRENT_DATE
ORDER BY i.email
`

// Destinatarios de un aviso. Filtra por suscripción activa y por cursada
// todavía vigente: el cierre por fecha se resuelve acá, sin proceso aparte.
func (q *Queries) ListActiveEmailsBySemester(ctx context.Context, idSemester uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEmailsBySemester, idSemester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInscriptionsBySemester = `-- name: ListInscriptionsBySemester :many
SELECT id_inscription, id_semester, email, active, created_at FROM inscriptions
WHERE id_semester = $1
ORDER BY created_at
`

func (q *Queries) ListInscriptionsBySemester(ctx context.Context, idSemester uuid.UUID) ([]Inscription, error) {
	rows, err := q.db.QueryContext(ctx, listInscriptionsBySemester, idSemester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inscription
	for rows.Next() {
		var i Inscription
		if err := rows.Scan(
			&i.IDInscription,
			&i.IDSemester,
			&i.Email,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInscriptionActive = `-- name: SetInscriptionActive :execrows
UPDATE inscriptions
SET active = $3
WHERE id_semester = $1 AND email = $2
`

type SetInscriptionActiveParams struct {
	IDSemester uuid.UUID `json:"id_semester"`
	Email      string    `json:"email"`
	Active     bool      `json:"active"`
}

// Un solo update para baja (false) y reactivación (true).
func (q *Queries) SetInscriptionActive(ctx context.Context, arg SetInscriptionActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInscriptionActive, arg.IDSemester, arg.Email, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
