// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Course struct {
	IDCourse uuid.UUID `json:"id_course"`
	Name     string    `json:"name"`
}

type Inscription struct {
	IDInscription uuid.UUID `json:"id_inscription"`
	IDSemester    uuid.UUID `json:"id_semester"`
	Email         string    `json:"email"`
	Active        bool      `json:"active"`
	CreatedAt     time.Time `json:"created_at"`
}

type Notice struct {
	IDNotice   uuid.UUID `json:"id_notice"`
	IDSemester uuid.UUID `json:"id_semester"`
	IDSender   uuid.UUID `json:"id_sender"`
	Title      string    `json:"title"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
}

type Semester struct {
	IDSemester  uuid.UUID `json:"id_semester"`
	IDCourse    uuid.UUID `json:"id_course"`
	ProfessorID uuid.UUID `json:"professor_id"`
	Year        int32     `json:"year"`
	SubToken    string    `json:"sub_token"`
	EndDate     time.Time `json:"end_date"`
}

type User struct {
	IDUser       uuid.UUID `json:"id_user"`
	Fullname     string    `json:"fullname"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}
