// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notices_queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNoticesBySemester = `-- name: CountNoticesBySemester :one
SELECT COUNT(*) FROM notices
WHERE id_semester = $1
`

func (q *Queries) CountNoticesBySemester(ctx context.Context, idSemester uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNoticesBySemester, idSemester)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotice = `-- name: CreateNotice :one
INSERT INTO notices (id_semester, id_sender, title, message)
VALUES ($1, $2, $3, $4)
RETURNING id_notice, id_semester, id_sender, title, message, created_at
`

type CreateNoticeParams struct {
	IDSemester uuid.UUID `json:"id_semester"`
	IDSender   uuid.UUID `json:"id_sender"`
	Title      string    `json:"title"`
	Message    string    `json:"message"`
}

func (q *Queries) CreateNotice(ctx context.Context, arg CreateNoticeParams) (Notice, error) {
	row := q.db.QueryRowContext(ctx, createNotice,
		arg.IDSemester,
		arg.IDSender,
		arg.Title,
		arg.Message,
	)
	var i Notice
	err := row.Scan(
		&i.IDNotice,
		&i.IDSemester,
		&i.IDSender,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotice = `-- name: DeleteNotice :execrows
DELETE FROM notices
WHERE id_notice = $1
`

func (q *Queries) DeleteNotice(ctx context.Context, idNotice uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotice, idNotice)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNoticeById = `-- name: GetNoticeById :one
SELECT id_notice, id_semester, id_sender, title, message, created_at FROM notices
WHERE id_notice = $1
`

func (q *Queries) GetNoticeById(ctx context.Context, idNotice uuid.UUID) (Notice, error) {
	row := q.db.QueryRowContext(ctx, getNoticeById, idNotice)
	var i Notice
	err := row.Scan(
		&i.IDNotice,
		&i.IDSemester,
		&i.IDSender,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listNotices = `-- name: ListNotices :many
SELECT id_notice, id_semester, id_sender, title, message, created_at FROM notices
ORDER BY created_at DESC
`

func (q *Queries) ListNotices(ctx context.Context) ([]Notice, error) {
	rows, err := q.db.QueryContext(ctx, listNotices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notice
	for rows.Next() {
		var i Notice
		if err := rows.Scan(
			&i.IDNotice,
			&i.IDSemester,
			&i.IDSender,
			&i.Title,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoticesBySemester = `-- name: ListNoticesBySemester :many
SELECT id_notice, id_semester, id_sender, title, message, created_at FROM notices
WHERE id_semester = $1
ORDER BY created_at DESC
`

// La que usa la pantalla real: historial de avisos de una cursada,
// del más reciente al más viejo.
func (q *Queries) ListNoticesBySemester(ctx context.Context, idSemester uuid.UUID) ([]Notice, error) {
	rows, err := q.db.QueryContext(ctx, listNoticesBySemester, idSemester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notice
	for rows.Next() {
		var i Notice
		if err := rows.Scan(
			&i.IDNotice,
			&i.IDSemester,
			&i.IDSender,
			&i.Title,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoticesWithSender = `-- name: ListNoticesWithSender :many
SELECT
    n.id_notice,
    n.id_semester,
    n.title,
    n.message,
    n.created_at,
    u.fullname AS sender_name
FROM notices n
JOIN users u ON u.id_user = n.id_sender
WHERE n.id_semester = $1
ORDER BY n.created_at DESC
`

type ListNoticesWithSenderRow struct {
	IDNotice   uuid.UUID `json:"id_notice"`
	IDSemester uuid.UUID `json:"id_semester"`
	Title      string    `json:"title"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"created_at"`
	SenderName string    `json:"sender_name"`
}

// Historial con el nombre del profesor que publicó cada aviso.
func (q *Queries) ListNoticesWithSender(ctx context.Context, idSemester uuid.UUID) ([]ListNoticesWithSenderRow, error) {
	rows, err := q.db.QueryContext(ctx, listNoticesWithSender, idSemester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoticesWithSenderRow
	for rows.Next() {
		var i ListNoticesWithSenderRow
		if err := rows.Scan(
			&i.IDNotice,
			&i.IDSemester,
			&i.Title,
			&i.Message,
			&i.CreatedAt,
			&i.SenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNoticeMessage = `-- name: UpdateNoticeMessage :one
UPDATE notices
SET message = $2
WHERE id_notice = $1
RETURNING id_notice, id_semester, id_sender, title, message, created_at
`

type UpdateNoticeMessageParams struct {
	IDNotice uuid.UUID `json:"id_notice"`
	Message  string    `json:"message"`
}

func (q *Queries) UpdateNoticeMessage(ctx context.Context, arg UpdateNoticeMessageParams) (Notice, error) {
	row := q.db.QueryRowContext(ctx, updateNoticeMessage, arg.IDNotice, arg.Message)
	var i Notice
	err := row.Scan(
		&i.IDNotice,
		&i.IDSemester,
		&i.IDSender,
		&i.Title,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
