// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: semesters_queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSemester = `-- name: CreateSemester :one
INSERT INTO semesters (id_course, professor_id, year, sub_token, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_semester, id_course, professor_id, year, sub_token, end_date
`

type CreateSemesterParams struct {
	IDCourse    uuid.UUID `json:"id_course"`
	ProfessorID uuid.UUID `json:"professor_id"`
	Year        int32     `json:"year"`
	SubToken    string    `json:"sub_token"`
	EndDate     time.Time `json:"end_date"`
}

func (q *Queries) CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error) {
	row := q.db.QueryRowContext(ctx, createSemester,
		arg.IDCourse,
		arg.ProfessorID,
		arg.Year,
		arg.SubToken,
		arg.EndDate,
	)
	var i Semester
	err := row.Scan(
		&i.IDSemester,
		&i.IDCourse,
		&i.ProfessorID,
		&i.Year,
		&i.SubToken,
		&i.EndDate,
	)
	return i, err
}

const deleteSemester = `-- name: DeleteSemester :execrows
DELETE FROM semesters
WHERE id_semester = $1
`

func (q *Queries) DeleteSemester(ctx context.Context, idSemester uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSemester, idSemester)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSemesterById = `-- name: GetSemesterById :one
SELECT id_semester, id_course, professor_id, year, sub_token, end_date FROM semesters
WHERE id_semester = $1
`

func (q *Queries) GetSemesterById(ctx context.Context, idSemester uuid.UUID) (Semester, error) {
	row := q.db.QueryRowContext(ctx, getSemesterById, idSemester)
	var i Semester
	err := row.Scan(
		&i.IDSemester,
		&i.IDCourse,
		&i.ProfessorID,
		&i.Year,
		&i.SubToken,
		&i.EndDate,
	)
	return i, err
}

const getSemesterByToken = `-- name: GetSemesterByToken :one
SELECT
    s.id_semester,
    s.id_course,
    s.professor_id,
    s.year,
    s.sub_token,
    s.end_date,
    c.name AS course_name,
    (s.end_date >= CURRENT_DATE) AS is_open
FROM semesters s
JOIN courses c ON c.id_course = s.id_course
WHERE s.sub_token = $1
`

type GetSemesterByTokenRow struct {
	IDSemester  uuid.UUID `json:"id_semester"`
	IDCourse    uuid.UUID `json:"id_course"`
	ProfessorID uuid.UUID `json:"professor_id"`
	Year        int32     `json:"year"`
	SubToken    string    `json:"sub_token"`
	EndDate     time.Time `json:"end_date"`
	CourseName  string    `json:"course_name"`
	IsOpen      bool      `json:"is_open"`
}

// Resuelve el QR/link de suscripción. Devuelve también el nombre de la materia
// y si la cursada sigue abierta, que es lo que la pantalla necesita mostrar.
func (q *Queries) GetSemesterByToken(ctx context.Context, subToken string) (GetSemesterByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSemesterByToken, subToken)
	var i GetSemesterByTokenRow
	err := row.Scan(
		&i.IDSemester,
		&i.IDCourse,
		&i.ProfessorID,
		&i.Year,
		&i.SubToken,
		&i.EndDate,
		&i.CourseName,
		&i.IsOpen,
	)
	return i, err
}

const listSemestersByCourse = `-- name: ListSemestersByCourse :many
SELECT id_semester, id_course, professor_id, year, sub_token, end_date FROM semesters
WHERE id_course = $1
ORDER BY year DESC
`

func (q *Queries) ListSemestersByCourse(ctx context.Context, idCourse uuid.UUID) ([]Semester, error) {
	rows, err := q.db.QueryContext(ctx, listSemestersByCourse, idCourse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Semester
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.IDSemester,
			&i.IDCourse,
			&i.ProfessorID,
			&i.Year,
			&i.SubToken,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemestersByProfessor = `-- name: ListSemestersByProfessor :many
SELECT
    s.id_semester,
    s.year,
    s.sub_token,
    s.end_date,
    c.name AS course_name,
    COUNT(i.id_inscription) FILTER (WHERE i.active) AS active_subscribers
FROM semesters s
JOIN courses c ON c.id_course = s.id_course
LEFT JOIN inscriptions i ON i.id_semester = s.id_semester
WHERE s.professor_id = $1
GROUP BY s.id_semester, c.name
ORDER BY s.year DESC, c.name
`

type ListSemestersByProfessorRow struct {
	IDSemester        uuid.UUID `json:"id_semester"`
	Year              int32     `json:"year"`
	SubToken          string    `json:"sub_token"`
	EndDate           time.Time `json:"end_date"`
	CourseName        string    `json:"course_name"`
	ActiveSubscribers int64     `json:"active_subscribers"`
}

// Panel del profesor: sus cursadas con el nombre de la materia y el conteo
// de suscriptos activos.
func (q *Queries) ListSemestersByProfessor(ctx context.Context, professorID uuid.UUID) ([]ListSemestersByProfessorRow, error) {
	rows, err := q.db.QueryContext(ctx, listSemestersByProfessor, professorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSemestersByProfessorRow
	for rows.Next() {
		var i ListSemestersByProfessorRow
		if err := rows.Scan(
			&i.IDSemester,
			&i.Year,
			&i.SubToken,
			&i.EndDate,
			&i.CourseName,
			&i.ActiveSubscribers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSemesterEndDate = `-- name: UpdateSemesterEndDate :one
UPDATE semesters
SET end_date = $2
WHERE id_semester = $1
RETURNING id_semester, id_course, professor_id, year, sub_token, end_date
`

type UpdateSemesterEndDateParams struct {
	IDSemester uuid.UUID `json:"id_semester"`
	EndDate    time.Time `json:"end_date"`
}

// Sirve tanto para corregir la fecha como para cerrar la cursada antes de
// tiempo, poniendo la fecha de hoy.
func (q *Queries) UpdateSemesterEndDate(ctx context.Context, arg UpdateSemesterEndDateParams) (Semester, error) {
	row := q.db.QueryRowContext(ctx, updateSemesterEndDate, arg.IDSemester, arg.EndDate)
	var i Semester
	err := row.Scan(
		&i.IDSemester,
		&i.IDCourse,
		&i.ProfessorID,
		&i.Year,
		&i.SubToken,
		&i.EndDate,
	)
	return i, err
}
