// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (fullname, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id_user, fullname, email, password_hash
`

type CreateUserParams struct {
	Fullname     string `json:"fullname"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Fullname, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id_user = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUser uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, idUser)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id_user, fullname, email, password_hash FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id_user, fullname, email, password_hash FROM users
WHERE id_user = $1
`

func (q *Queries) GetUserById(ctx context.Context, idUser uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, idUser)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id_user, fullname, email FROM users
ORDER BY fullname
`

type ListUsersRow struct {
	IDUser   uuid.UUID `json:"id_user"`
	Fullname string    `json:"fullname"`
	Email    string    `json:"email"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.IDUser, &i.Fullname, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserFullname = `-- name: UpdateUserFullname :one
UPDATE users
SET fullname = $2
WHERE id_user = $1
RETURNING id_user, fullname, email, password_hash
`

type UpdateUserFullnameParams struct {
	IDUser   uuid.UUID `json:"id_user"`
	Fullname string    `json:"fullname"`
}

func (q *Queries) UpdateUserFullname(ctx context.Context, arg UpdateUserFullnameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserFullname, arg.IDUser, arg.Fullname)
	var i User
	err := row.Scan(
		&i.IDUser,
		&i.Fullname,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $2
WHERE id_user = $1
`

type UpdateUserPasswordParams struct {
	IDUser       uuid.UUID `json:"id_user"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.IDUser, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
